name = input("What is your name: ")
age = input("What is your age: ")
print ('hello ' + name + ', you are ' + age + ' years old')
tillOH = 100 - int(age)
tillOH = str(tillOH)
print (f'you will turn 100 in ' + tillOH + ' years')